#!/usr/bin/env python3
import os
import subprocess
import yaml
import xml.etree.ElementTree as ET
import glob
import re

# ==========================================
# Configuration
# ==========================================
XML_CONFIG = "CMSIT.xml"
CHIP_ID = 0
YAML_GEO = "sensor_geometry.yaml"
TOLERANCE_PERCENT = 5.0
MAX_ITERATIONS = 6
PREAMP_ABSOLUTE_MIN = 200
PREAMP_ABSOLUTE_MAX = 600

# Sync Parameters for scurve_launch and scurve_graph
NUM_SCANS = 32
RUNS_PER_DELAY = 3

# Physical surface area map for RD53B/CROC (um^2)
PIXEL_AREAS = {
    'Macro_Corner': 87.5 * 225.0,  # 19687.5
    'Long_Row':     25.0 * 225.0,  # 5625.0
    'Long_Col':     87.5 * 100.0,  # 8750.0
    'Standard':     25.0 * 100.0,  # 2500.0
    'Default':      25.0 * 100.0
}

def get_next_run_number(results_dir="Results"):
    """Finds the highest run number in the Results directory and adds 1."""
    if not os.path.exists(results_dir):
        return 1
        
    files = glob.glob(os.path.join(results_dir, "Run*_SCurve.root"))
    if not files:
        return 1
    
    run_numbers = []
    for f in files:
        match = re.search(r"Run(\d+)_", os.path.basename(f))
        if match:
            run_numbers.append(int(match.group(1)))
            
    return max(run_numbers) + 1 if run_numbers else 1

def get_dac_mappings(chip_id):
    """Parses sensor_geometry.yaml to return all available DAC register mappings."""
    with open(YAML_GEO, 'r') as file:
        geo = yaml.safe_load(file)
        
    config_key = 'chip_0_2' if chip_id in [0, 2] else 'chip_1_3'
    return geo[config_key]['preamp_dac_mapping'] 

def get_xml_register(xml_file, register_name, chip_id):
    tree = ET.parse(xml_file)
    for chip in tree.getroot().iter("RD53Bv2"):
        if chip.attrib.get("Id") == str(chip_id):
            return int(chip.find("Settings").attrib[register_name])
            
def update_xml_registers(xml_file, updates_dict, chip_id):
    tree = ET.parse(xml_file)
    for chip in tree.getroot().iter("RD53Bv2"):
        if chip.attrib.get("Id") == str(chip_id):
            settings = chip.find("Settings")
            for reg, val in updates_dict.items():
                settings.attrib[reg] = str(int(val))
    tree.write(xml_file, encoding="UTF-8", xml_declaration=True)

def evaluate_optimal_delays(chip_id):
    start_run = get_next_run_number()
    print(f"   -> Auto-detected next start_run: {start_run}")
    
    print("   -> Running scurve_launch.py...")
    subprocess.run(
        f"python3 scurve_launch.py --xml_filename {XML_CONFIG} --num_scans {NUM_SCANS} --runs_per_delay {RUNS_PER_DELAY}", 
        shell=True, check=True
    )
    
    print(f"   -> Running scurve_graph.py with --start_run {start_run}...")
    subprocess.run(
        f"python3 scurve_graph.py --start_run {start_run} --num_scans {NUM_SCANS} --runs_per_delay {RUNS_PER_DELAY}", 
        shell=True, check=True
    )
    
    delay_file = "optimal_delays.yaml"
    if not os.path.exists(delay_file):
        raise FileNotFoundError(f"Error: {delay_file} was not generated by scurve_graph.py")

    with open(delay_file, 'r') as file:
        all_delays = yaml.safe_load(file)
        
    chip_key = f"chip_{chip_id}"
    if chip_key not in all_delays:
        raise KeyError(f"Error: {chip_key} not found in {delay_file}")

    return all_delays[chip_key]

def main():
    dac_map = get_dac_mappings(CHIP_ID)
    
    print("**Step 1: Running Initial Baseline Evaluation**")
    opt_delays = evaluate_optimal_delays(CHIP_ID)
    
    # Auto-infer reference pixel (the one with the smallest physical area)
    found_geometries = list(opt_delays.keys())
    if not found_geometries:
        raise ValueError("No valid pixel geometries were returned by scurve_graph.py")
        
    reference_type = min(found_geometries, key=lambda k: PIXEL_AREAS.get(k, float('inf')))
    opt_std = opt_delays[reference_type]
    
    # Any type found in the output that isn't the smallest and has a mapped DAC becomes a target
    target_types = [p for p in found_geometries if p != reference_type and p in dac_map]
    
    print(f"\n**Auto-Detection Complete**")
    print(f"  Reference Pixel (Smallest Area): {reference_type} (Opt Delay = {opt_std:.2f})")
    print(f"  Target Geometries for Alignment: {target_types}\n")
    
    if not target_types:
        print("No target geometries require alignment. Exiting.")
        return

    # Initialize search state
    search_state = {}
    for p_type in target_types:
        reg_name = dac_map[p_type]
        current_val = get_xml_register(XML_CONFIG, reg_name, CHIP_ID)
        search_state[p_type] = {
            'reg': reg_name,
            'current': current_val,
            'low': PREAMP_ABSOLUTE_MIN,
            'high': PREAMP_ABSOLUTE_MAX,
            'converged': False
        }
    
    # Evaluate initial bounds
    for p_type in target_types:
        state = search_state[p_type]
        opt_val = opt_delays[p_type]
        err = (abs(opt_val - opt_std) / opt_std) * 100.0
        
        print(f"Initial State - {p_type} ({state['reg']}): Min = {opt_val:.2f} | Err = {err:.2f}%")
        
        if err <= TOLERANCE_PERCENT:
            state['converged'] = True
        elif opt_val > opt_std:
            state['high'] = state['current'] 
        else:
            state['low'] = state['current']  

    # Synchronous Binary Search Loop
    for iteration in range(1, MAX_ITERATIONS + 1):
        active_targets = [p for p in target_types if not search_state[p]['converged']]
        if not active_targets:
            print("\n**SUCCESS:** All target geometries converged!")
            break
            
        print(f"\n**Iteration {iteration}: Updating Registers**")
        updates = {}
        for p_type in active_targets:
            state = search_state[p_type]
            if state['low'] > state['high']:
                print(f"Warning: Bounds collapsed for {p_type}. Forcing convergence.")
                state['converged'] = True
                continue
                
            mid = int((state['low'] + state['high']) / 2)
            state['current'] = mid
            updates[state['reg']] = mid
            print(f"Testing {state['reg']} = {mid}")
            
        if updates:
            update_xml_registers(XML_CONFIG, updates, CHIP_ID)
            opt_delays = evaluate_optimal_delays(CHIP_ID)
            opt_std = opt_delays[reference_type]
            
            for p_type in active_targets:
                state = search_state[p_type]
                opt_val = opt_delays[p_type]
                err = (abs(opt_val - opt_std) / opt_std) * 100.0
                
                print(f"Result {p_type}: Min = {opt_val:.2f} | Err = {err:.2f}%")
                if err <= TOLERANCE_PERCENT:
                    state['converged'] = True
                elif opt_val > opt_std:
                    state['high'] = state['current'] - 1
                else:
                    state['low'] = state['current'] + 1

    print("\n**Final Configuration Locked:**")
    for p_type in target_types:
        print(f"  {p_type}: {search_state[p_type]['reg']} = {search_state[p_type]['current']}")

if __name__ == "__main__":
    main()
